version: '3'

services:
  mobilization-classifier:
    image: erancha/urbangeopulse:mobilization-classifier-1.0
    networks:
      - urbangeopulse-net
    env_file:
      - ./kafka-vars.env
    environment:
      REDIS_HOST_NAME: redis-server
      PEOPLE_GEO_LOCATIONS_TOPIC_NAME: people_geo_locations
      PEDESTRIANS_GEO_LOCATIONS_TOPIC_NAME: pedestrians_geo_locations
      MOBILIZED_GEO_LOCATIONS_TOPIC_NAME: mobilized_geo_locations
      MOBILIZATION_CLASSIFIER_CONSUMER_THREADS_COUNT: 60
      MOBILIZATION_CLASSIFIER_AUTO_OFFSET_RESET_CONFIG: earliest
      MOBILIZATION_CLASSIFIER_SESSION_TIMEOUT_SECONDS_CONFIG: 120
    depends_on:
      - kafka-broker

networks:
  urbangeopulse-net:
    external:
      name: urbangeopulse-net
