version: '3'

services:
  activity-aggregator-pedestrians-streets:
    image: erancha/urbangeopulse:activity-aggregator-1.0
    networks:
      - urbangeopulse-net
    env_file:
      - ./kafka-vars.env
      - ./pg-vars.env
      - ./activity-aggregator-vars.env
    environment:
      # TODO: Try to reuse env variables as in basic-implementation\scripts\development
      ACTIVITY_AGGREGATOR_PERSISTENCE_INTERVAL_SEC: 20
      # ACTIVITY_AGGREGATOR_CONSUMER_THREADS_COUNT: 2
    depends_on:
      - kafka-broker
      - postgis-server-nyc

  activity-aggregator-pedestrians-neighborhoods:
    image: erancha/urbangeopulse:activity-aggregator-1.0
    networks:
      - urbangeopulse-net
    env_file:
      - ./kafka-vars.env
      - ./pg-vars.env
      - ./activity-aggregator-vars.env
    environment:
      # TODO: Try to reuse env variables as in basic-implementation\scripts\development
    depends_on:
      - kafka-broker
      - postgis-server-nyc

  # activity-aggregator-mobilized-streets:
    # image: erancha/urbangeopulse:activity-aggregator-1.0
    # networks:
      # - urbangeopulse-net
    # env_file:
      # - ./kafka-vars.env
      # - ./pg-vars.env
      # - ./activity-aggregator-vars.env
    # environment:
      # TODO: Try to reuse env variables as in basic-implementation\scripts\development
    # depends_on:
      # - kafka-broker
      # - postgis-server-nyc

  # activity-aggregator-mobilized-neighborhoods:
    # image: erancha/urbangeopulse:activity-aggregator-1.0
    # networks:
      # - urbangeopulse-net
    # env_file:
      # - ./kafka-vars.env
      # - ./pg-vars.env
      # - ./activity-aggregator-vars.env
    # environment:
      # TODO: Try to reuse env variables as in basic-implementation\scripts\development
    # depends_on:
      # - kafka-broker
      # - postgis-server-nyc

networks:
  urbangeopulse-net:
    external:
      name: urbangeopulse-net
